---
# Implement your Pre Workload deployment tasks here
# -------------------------------------------------

- name: Role agp_devspaces | Task pre_workload | Create DevSpaces namespace
  kubernetes.core.k8s:
    state: "{{ agp_devspaces_state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ agp_devspaces_operator_devspaces_namespace }}"

- name: Role agp_devspaces | Task pre_workload | Create operator catalog
  when: agp_devspaces_operator_catalog_create
  kubernetes.core.k8s:
    state: "{{ agp_devspaces_state }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      metadata:
        name: "{{ agp_devspaces_operator_catalog_name }}"
        namespace: "{{ agp_devspaces_operator_catalog_namespace }}"
      spec:
        spec:
        displayName: "{{ agp_devspaces_operator_catalog_display_name }}"
        image: "{{ agp_devspaces_operator_catalog_image }}:{{ agp_devspaces_operator_catalog_image_tag }}"
        publisher: "{{ agp_devspaces_operator_catalog_publisher }}"
        sourceType: "{{ agp_devspaces_operator_catalog_source_type }}"
    wait: true
    # wait_condition:
    #   type: connectionState
    #   status: true
    #   reason: "READY"


# Leave these as the last tasks in the playbook
# ---------------------------------------------

# For deployment onto a dedicated cluster (as part of the
# cluster deployment) set workload_shared_deployment to False
# This is the default so it does not have to be set explicitely
- name: Role agp_devspaces | Task pre_workload | pre_workload tasks complete
  ansible.builtin.debug:
    msg: "Pre-Workload tasks completed successfully."
  when:
    - not agp_devspaces_silent | bool
    - not workload_shared_deployment | default(false) | bool

# For RHPDS deployment (onto a shared cluster) set
# workload_shared_deployment to True
# (in the deploy script or AgnosticV configuration)
- name: Role agp_devspaces | Task pre_workload | pre_workload tasks complete
  ansible.builtin.debug:
    msg: "Pre-Software checks completed successfully"
  when:
    - not agp_devspaces_silent | bool
    - workload_shared_deployment | default(false) | bool
